### ISSUE TITLE
Save game time is two hours out

### ISSUE THREAD

**Issue by robertc** [virtual-programming/bioshockinfinite-linux#12]
The below screenshot was taken at 12:15:09. I'm exiting the game just after an area transition and waiting for the 'saving profile' graphic to disappear, so the 10:14:57 reported as the last save time is two hours out.  I started noticing this after the clocks changed for BST.

![2015-04-26_00002](https://cloud.githubusercontent.com/assets/46539/7336966/2cf3117a-ec0e-11e4-9ae6-3be767e02bb7.jpg)

[Steam system information](https://gist.github.com/robertc/59bea39cb2317ff133ef)

**Comment by vpltd-peterm** [comment]
Our time zone handling code had some pretty major bugs that did not show up when we were on GMT. They have been addressed now and this should be fixed in the next release.

Unfortunately existing saves will still have incorrect times, because the game is actually storing the time stamp as part of the file name (yes, I know this is silly). You may be able to rename affected saves if it really bugs you.

**Comment by robertc** [comment]
I noticed the same issue in Witcher 2 the other night, I assume it's the same problem?  If you'd like me to log an issue there as well let me know.

I'm not really too bothered about the filenames myself. It was that moment of horror, the first time it happened, when I thought I might be about to lose 2 hours of progress that was the worst thing.  Fortunately I've written and debugged enough incorrect timezone code myself to spot the symptoms once I'd calmed down :)

**Comment by vpltd-peterm** [comment]
Please do log an issue against Witcher 2 if it's affected - the same code changes ive made for this will probably fix it there, too!

**Comment by robertc** [comment]
[Logged an issue for Witcher 2](https://github.com/virtual-programming/witcher2-linux/issues/128), it's not quite the same problem after all.

**Comment by robertc** [comment]
Saved a game just now, the time was correct.
