### ISSUE TITLE
Incorrect amount of VRAM detected

### ISSUE THREAD

**Issue by not83** [virtual-programming/bioshockinfinite-linux#35]
https://www.reddit.com/r/linux_gaming/comments/3nieya/heres_a_fix_for_bioshocks_stuttering_and_texture/ says that this game does correctly detect the amount of VRAM.

"changing PoolSize=400 to something like PoolSize=3000 (depending on the amount of VRAM you have) fixed both stuttering and popping issues. Look for this setting in /home/<user>/.local/share/Steam/SteamApps/common/BioShock Infinite/XGame/Config/DefaultEngine.ini"

This would be best to fix this issue because people on SteamOS will not be editing files etc

**Comment by vpltd-peterm** [comment]
Currently we report to the game via Direct3D API's the amount of VRAM the GPU has, where its available.. this is done by using GL_NVX_gpu_memory_info on the nvidia driver,  GL_ATI_meminfo on AMD Catalyst, and GLX_MESA_query_renderer on MESA based drivers. The figure reported is exactly the same as on Windows in this regard.

What increasing PoolSize does do, is make up for the fact that GL does not cope very well with Unreal Engine's realtime texture streaming. This is more of a flaw with GL/UnrealEngine itself, rather than eON. We do have word that even natively, UE has issues with this.

**Comment by not83** [comment]
Understood.
