### ISSUE TITLE
Game doesn't work on amd open source driver

### ISSUE THREAD

**Issue by Algram** [virtual-programming/bioshockinfinite-linux#7]
I know this problem is due to requirements that the os-driver does not support, but maybe there is a way to turn those features off?

**Comment by vpltd-peterm** [comment]
No. The game makes use of OpenGL 4 feature set, and this cannot be avoided.

**Comment by Nimroot** [comment]
@Algram mesa probably will support OpenGL 4.X (I'd guess it'd be 4.2) with its September(?) release later this year, so unless you could wait you'll have to use fglrx.

**Comment by ChristophHaag** [comment]
The steam site says more specifically OpenGL 4.1.

Only a very small opinion: It's totally fine to require a recent OpenGL version and there is no obligation whatsoever for game / wrapper developers to support old versions. It's mesa's responsibility to support newer versions.

That said, it probably wouldn't be worth the effort, because OpenGL 4 support will come soon. The current status of mesa can be seen here: http://cgit.freedesktop.org/mesa/mesa/tree/docs/GL3.txt

Tesselation is actually almost ready and according to a driver developer can already run Unigine Heaven: https://www.phoronix.com/forums/showthread.php?117129-DRM-Graphics-Updates-Sent-In-For-The-Linux-4-1-Kernel&p=484756#post484756

Driver developers also said that almost nobody uses GL_ARB_shader_subroutine, so there is a chance it will run very soon already with overriding the mesa opengl version even when the OpenGL version isn't officially supported. For that matter it would be a nice touch if all the required OpenGL extensions were listed in the system requirements.
